name: Pull Request Comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  job1:
    # This condition ensures that the job only runs if the comment is on a pull request
    if: github.event.issue.pull_request != ''
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        # This condition checks if the comment contains the '/support' keyword
        if: contains(github.event.comment.body, '/support')
        run: echo "Hello from support!"

      - name: Test
        # This condition checks if the comment contains the '/test' keyword
        if: contains(github.event.comment.body, '/test')
        run: echo "Running tests!"
      - name: yet another one
        if: startsWith(github.event.comment.body, '/ci')
        run: echo "Running tests!"

  job2:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && startsWith(github.event.comment.body, '/run ci')
    steps:
      - name: Run CI
        run: echo "Running CI!"
